name: Build & Deploy to GCP VM

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  REPO_NAME: gcp-vm

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Authenticate to GCP (OIDC)
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Build Docker Image
      run: |
        IMAGE="us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/app:latest"
        docker build -t "$IMAGE" .
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Push Docker Image
      run: |
        docker push "$IMAGE"

    - name: Init Terraform
      working-directory: infra/terraform
      run: terraform init

    - name: Apply Terraform
      working-directory: infra/terraform
      run: terraform apply -auto-approve

    - name: Deploy App to VM (SSH)
      run: |
        VM_IP="$(gcloud compute instances describe backend-vm --zone=us-central1-a --format='value(networkInterfaces[0].accessConfigs[0].natIP)')"

        echo "VM IP: \$VM_IP"

        gcloud compute ssh ubuntu@backend-vm \
          --zone=us-central1-a \
          --command="\
            sudo docker pull ${IMAGE} && \
            sudo docker stop app || true && \
            sudo docker rm app || true && \
            sudo docker run -d --name app -p 80:80 ${IMAGE} \
          "
